spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scs_io
    username: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
NgMantisExtractor:
  max-retry: 30
  mantis-db-url: jdbc:mysql://localhost:3306/bugtracker